### ISSUE TITLE
problem while unpacking

### ISSUE THREAD

**Issue by urupz** [AtomCrafty/yukatool2#3]
![N6X0F0QXcS](https://user-images.githubusercontent.com/33509958/87827546-4ae67e00-c8a5-11ea-8bc9-d2f4cf890ec6.png)
game: https://vndb.org/v11086
file: data01.ykc

**Comment by AtomCrafty** [comment]
Thanks for the report. Could you maybe extract the archive without converting (`yuka unpack --raw data1.ykc`) and upload the problematic ykg image file? The formats differ slightly between the various versions of the engine.

**Comment by urupz** [comment]
> Thanks for the report. Could you maybe extract the archive without converting (`yuka unpack --raw data1.ykc`) and upload the problematic ykg image file? The formats differ slightly between the various versions of the engine.

[window01_batu_dummy.zip](https://github.com/AtomCrafty/yukatool2/files/4940108/window01_batu_dummy.zip)

**Comment by AtomCrafty** [comment]
Thanks, I'll have a look at it when I'm free.

**Comment by urupz** [comment]
sure, take your time

**Comment by AtomCrafty** [comment]
Alright, managed to pinpoint the issue. The ykg file you provided does not contain any image data, just animation data. That's why the png decode fails. This shouldn't be a problem though, during package extraction it should generate a file called `window01_batu_dummy.ani` with no corresponding png file. If you plan to repack the files at some point, you might need to replace this .ani file by the original .ykg file.

**Comment by urupz** [comment]
thanks, i got it
