### ISSUE TITLE
Filename case is not preserved on unpack.

### ISSUE THREAD

**Issue by Andrei-Stakov** [AtomCrafty/yukatool2#5]
Found this issue while searching clues for #4 .

With a repackaged .ykc from the original with no modified files, the game engine refuses to use the contained files and popups a missing file warning. Noticed that the path shown in the popup was having uppercase filename, I tried to batch-converted all related files (that were considered as missing by the engine) to uppercase, `pack `it up again, and now it runs perfectly.

This might be a combination of few possible points:

- The engine itself is only recognizing case-sensitive filenames (ARGH!).
- YukaTool somehow ignored or can't recognized the filename case from the archive and just use lowercase for decompiled files on `unpack`. It's the same with YukaTool GUI, as the original .ykc, the repacked .ykc, and the fixed .ykc was showing the same, lowercased files and folders.
- YukaTool properly preserved the filename case on `pack`.

I've experimented with a simple directory with various cased files and folders, and it was clear that `unpack` isn't properly preserving the filename case, as in this screenshot:
![image](https://user-images.githubusercontent.com/16612525/108452106-81043a00-729a-11eb-8b41-e584e7213171.png)

I'll include the sample directory case (with various cased filenames) for easier analysis.
[test.zip](https://github.com/AtomCrafty/yukatool2/files/6007241/test.zip)

Here's the tree-list for the packed .ykc of the sample case, seen through YukaTool GUI:
![image](https://user-images.githubusercontent.com/16612525/108449204-a8a4d380-7295-11eb-81e9-7ddc55e54201.png)

**Comment by AtomCrafty** [comment]
The file name normalization was an intentional design choice, because I was fed up with the inconsistent naming used by some devs. I'm surprised this is causing any issues, the engine version I worked with accepted the lowercase files just fine.

Anyway, in [release 2.5](https://github.com/AtomCrafty/yukatool2/releases/tag/v2.5) I added the command line option `--normalize-case=false` to disable the normalization.  
And while I was at it I also created a `list` command so you don't have to check with YukaTool GUI every time ^^

![image](https://user-images.githubusercontent.com/4553050/108464685-eea36c80-7280-11eb-937b-a39eca6c379c.png)

**Comment by Andrei-Stakov** [comment]
Thank you for the awesome help 😄 ! This would surely saves me a lot of headache.

Yeah, it's a surprise for me too, since normally they wouldn't want to tire themselves out regarding filename case in a complex game like this. I hope that this is just particularly specific to this game only, and not spread out to the rest of PeasSoft's other games.

Again, thank you very much for such a swift responses and assistance!
